# Generated by Django 6.0 on 2026-02-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='safer_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
