# Generated by Django 6.0 on 2026-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_post_text_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='toxic_score',
            field=models.FloatField(default=0.0),
        ),
    ]
