# Generated by Django 4.2.8 on 2026-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='originally_toxic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='originally_toxic',
            field=models.BooleanField(default=False),
        ),
    ]
